import type React from 'react';
import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  X,
  Mail,
  Linkedin,
  Share2,
  Copy,
  Check,
  ExternalLink,
  MessageSquare,
  Sparkles,
  Smartphone,
} from 'lucide-react';
import { toast } from 'sonner';
import type { NormalizedReport } from '../../utils/normalizeReport';
import { getGrade } from '../../utils/normalizeReport';

export interface ShareModalProps {
  isOpen: boolean;
  onClose: () => void;
  candidate: {
    id?: string;
    name: string;
    email: string;
  };
  assessment: {
    jobTitle: string;
    roundType?: string;
  };
  report: NormalizedReport;
}

export default function ShareModal({
  isOpen,
  onClose,
  candidate,
  assessment,
  report,
}: ShareModalProps) {
  const [copiedLink, setCopiedLink] = useState(false);
  const [copiedSummary, setCopiedSummary] = useState(false);

  if (!isOpen) return null;

  const round = report.meta.roundType || assessment.roundType || 'Interview';
  const score = report.overall.overallScore;
  const grade = getGrade(score);
  const comm = report.overall.communication?.overall_score ?? report.overall.communication?.overallScore ?? null;
  const conf = report.overall.confidenceScore;

  // Build current report URL
  const reportUrl = typeof window !== 'undefined'
    ? `${window.location.origin}${window.location.pathname}?candidate=${candidate.id || ''}`
    : '';

  // Clean, professional summary text
  const summaryText = [
    `🎯 Candidate Evaluation Summary: ${candidate.name}`,
    `Role: ${assessment.jobTitle} (${round} Round)`,
    score !== null ? `Overall Score: ${score}/100 (Grade ${grade.letter})` : null,
    comm !== null ? `Communication: ${Math.round(comm)}/100` : null,
    conf !== null ? `Confidence: ${Math.round(conf)}/100` : null,
    `Evaluated Questions: ${report.questions.length}`,
    reportUrl ? `Full Report Link: ${reportUrl}` : null,
    `Generated by PrimeHire & VILS AI Assessment Engine`,
  ]
    .filter(Boolean)
    .join('\n');

  const emailSubject = `Candidate Evaluation Report: ${candidate.name} - ${assessment.jobTitle}`;
  const emailBody = `Hi Team,\n\nPlease find the interview evaluation summary for ${candidate.name}:\n\n` +
    `• Candidate: ${candidate.name} (${candidate.email})\n` +
    `• Position: ${assessment.jobTitle}\n` +
    `• Round: ${round} Round\n` +
    (score !== null ? `• Overall Performance: ${score}/100 (Grade ${grade.letter})\n` : '') +
    (comm !== null ? `• Communication: ${Math.round(comm)}/100\n` : '') +
    (conf !== null ? `• Confidence: ${Math.round(conf)}/100\n` : '') +
    `\nView complete interactive breakdown & video responses here:\n${reportUrl}\n\n` +
    `Best regards,\nPrimeHire AI Assessment Platform`;

  // 1. Share via Gmail Web
  const handleShareGmail = () => {
    const gmailUrl = `https://mail.google.com/mail/?view=cm&fs=1&su=${encodeURIComponent(emailSubject)}&body=${encodeURIComponent(emailBody)}`;
    window.open(gmailUrl, '_blank', 'noopener,noreferrer');
    toast.success('Opened Gmail compose window!');
  };

  // 2. Share via Default Email Client
  const handleShareEmail = () => {
    const mailto = `mailto:?subject=${encodeURIComponent(emailSubject)}&body=${encodeURIComponent(emailBody)}`;
    window.location.href = mailto;
    toast.success('Opened email client!');
  };

  // 3. Share via LinkedIn
  const handleShareLinkedIn = () => {
    // Copy summary so user can easily paste it into LinkedIn post or message
    try {
      navigator.clipboard.writeText(summaryText);
    } catch {
      /* ignore */
    }
    const liUrl = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(reportUrl || window.location.href)}`;
    window.open(liUrl, '_blank', 'noopener,noreferrer');
    toast.success('Summary copied! Opening LinkedIn sharing dialog...');
  };

  // 4. Share via WhatsApp
  const handleShareWhatsApp = () => {
    const waUrl = `https://api.whatsapp.com/send?text=${encodeURIComponent(summaryText)}`;
    window.open(waUrl, '_blank', 'noopener,noreferrer');
    toast.success('Opening WhatsApp...');
  };

  // 5. Copy Full Summary
  const handleCopySummary = async () => {
    try {
      await navigator.clipboard.writeText(summaryText);
      setCopiedSummary(true);
      toast.success('Evaluation summary copied to clipboard!');
      setTimeout(() => setCopiedSummary(false), 2000);
    } catch {
      toast.error('Unable to copy to clipboard.');
    }
  };

  // 6. Copy Direct Link
  const handleCopyLink = async () => {
    try {
      await navigator.clipboard.writeText(reportUrl || window.location.href);
      setCopiedLink(true);
      toast.success('Report link copied to clipboard!');
      setTimeout(() => setCopiedLink(false), 2000);
    } catch {
      toast.error('Unable to copy link.');
    }
  };

  // 7. System / Mobile Share API (if supported)
  const canNativeShare = typeof navigator !== 'undefined' && !!navigator.share;
  const handleNativeShare = async () => {
    if (!navigator.share) return;
    try {
      await navigator.share({
        title: `PrimeHire Report: ${candidate.name}`,
        text: summaryText,
        url: reportUrl || window.location.href,
      });
      toast.success('Shared successfully!');
      onClose();
    } catch (err) {
      // User cancelled share
    }
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs">
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 10 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 10 }}
          transition={{ duration: 0.2 }}
          className="relative w-full max-w-lg overflow-hidden rounded-2xl border border-slate-200 bg-white p-6 shadow-2xl dark:border-slate-800 dark:bg-slate-900"
          role="dialog"
          aria-modal="true"
          aria-labelledby="share-modal-title"
        >
          {/* Header */}
          <div className="flex items-start justify-between border-b border-slate-100 pb-4 dark:border-slate-800">
            <div>
              <div className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-amber-600 dark:text-amber-400">
                <Share2 size={13} />
                Share Candidate Report
              </div>
              <h2 id="share-modal-title" className="mt-1 text-lg font-bold text-slate-900 dark:text-white">
                {candidate.name}
              </h2>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                {assessment.jobTitle} · {round} Round {score !== null ? `· ${score}/100 (Grade ${grade.letter})` : ''}
              </p>
            </div>
            <button
              type="button"
              onClick={onClose}
              className="rounded-full p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-600 dark:hover:bg-slate-800 dark:hover:text-slate-300"
              aria-label="Close dialog"
            >
              <X size={18} />
            </button>
          </div>

          {/* Quick Share Platforms */}
          <div className="mt-5 space-y-4">
            <p className="text-xs font-semibold text-slate-700 dark:text-slate-300">
              Select destination to share candidate report:
            </p>

            <div className="grid grid-cols-2 gap-2.5 sm:grid-cols-2">
              {/* Gmail Button */}
              <button
                type="button"
                onClick={handleShareGmail}
                className="flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50/60 p-3 text-left transition-all hover:border-amber-300 hover:bg-amber-50/50 hover:shadow-xs dark:border-slate-800 dark:bg-slate-800/60 dark:hover:border-amber-500"
              >
                <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-red-500 text-white shadow-xs">
                  <Mail size={18} />
                </div>
                <div className="min-w-0">
                  <p className="text-xs font-bold text-slate-900 dark:text-white">Gmail</p>
                  <p className="truncate text-[11px] text-slate-500 dark:text-slate-400">Compose in Gmail</p>
                </div>
              </button>

              {/* LinkedIn Button */}
              <button
                type="button"
                onClick={handleShareLinkedIn}
                className="flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50/60 p-3 text-left transition-all hover:border-amber-300 hover:bg-amber-50/50 hover:shadow-xs dark:border-slate-800 dark:bg-slate-800/60 dark:hover:border-amber-500"
              >
                <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-[#0077b5] text-white shadow-xs">
                  <Linkedin size={18} />
                </div>
                <div className="min-w-0">
                  <p className="text-xs font-bold text-slate-900 dark:text-white">LinkedIn</p>
                  <p className="truncate text-[11px] text-slate-500 dark:text-slate-400">Share or message</p>
                </div>
              </button>

              {/* WhatsApp Button */}
              <button
                type="button"
                onClick={handleShareWhatsApp}
                className="flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50/60 p-3 text-left transition-all hover:border-amber-300 hover:bg-amber-50/50 hover:shadow-xs dark:border-slate-800 dark:bg-slate-800/60 dark:hover:border-amber-500"
              >
                <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-[#25D366] text-white shadow-xs">
                  <MessageSquare size={18} />
                </div>
                <div className="min-w-0">
                  <p className="text-xs font-bold text-slate-900 dark:text-white">WhatsApp</p>
                  <p className="truncate text-[11px] text-slate-500 dark:text-slate-400">Send to chat/group</p>
                </div>
              </button>

              {/* Default Mail Client */}
              <button
                type="button"
                onClick={handleShareEmail}
                className="flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50/60 p-3 text-left transition-all hover:border-amber-300 hover:bg-amber-50/50 hover:shadow-xs dark:border-slate-800 dark:bg-slate-800/60 dark:hover:border-amber-500"
              >
                <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-amber-600 text-white shadow-xs">
                  <ExternalLink size={18} />
                </div>
                <div className="min-w-0">
                  <p className="text-xs font-bold text-slate-900 dark:text-white">Default Email</p>
                  <p className="truncate text-[11px] text-slate-500 dark:text-slate-400">Outlook / Apple Mail</p>
                </div>
              </button>
            </div>

            {/* Native OS Share (if supported) */}
            {canNativeShare && (
              <button
                type="button"
                onClick={handleNativeShare}
                className="flex w-full items-center justify-center gap-2 rounded-xl border border-amber-200 bg-amber-50 py-2.5 text-xs font-bold text-amber-700 hover:bg-amber-100 transition-colors dark:border-amber-800 dark:bg-amber-950/60 dark:text-amber-300"
              >
                <Smartphone size={14} />
                Open Native Share Menu (Slack, Teams, etc.)
              </button>
            )}

            {/* Copy Actions */}
            <div className="mt-4 pt-3 border-t border-slate-100 dark:border-slate-800 space-y-2">
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={handleCopySummary}
                  className="flex-1 inline-flex items-center justify-center gap-1.5 rounded-xl border border-slate-200 bg-white py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700"
                >
                  {copiedSummary ? <Check size={14} className="text-emerald-600" /> : <Sparkles size={14} className="text-amber-500" />}
                  {copiedSummary ? 'Summary Copied!' : 'Copy Formatted Summary'}
                </button>

                <button
                  type="button"
                  onClick={handleCopyLink}
                  className="flex-1 inline-flex items-center justify-center gap-1.5 rounded-xl border border-slate-200 bg-white py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700"
                >
                  {copiedLink ? <Check size={14} className="text-emerald-600" /> : <Copy size={14} />}
                  {copiedLink ? 'Link Copied!' : 'Copy Direct Link'}
                </button>
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
